/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef OTTER_SLICE_BAKE_CONFIG_H
#define OTTER_SLICE_BAKE_CONFIG_H

/* Headers of public dependencies */
/* No dependencies */

/* Convenience macro for exporting symbols */
#ifndef otter_slice_STATIC
#if defined(otter_slice_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define OTTER_SLICE_API __declspec(dllexport)
#elif defined(otter_slice_EXPORTS)
  #define OTTER_SLICE_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define OTTER_SLICE_API __declspec(dllimport)
#else
  #define OTTER_SLICE_API
#endif
#else
  #define OTTER_SLICE_API
#endif

#endif

